---
# file: postfix/handlers/main.yml
#
# handlers file.
#

- name: start postfix
  service:
    name=postfix
    state=started
  become: yes

- name: stop postfix
  service:
    name=postfix
    state=stopped
  become: yes

- name: restart postfix
  service:
    name=postfix
    state=restarted
  become: yes
